name: CI pipeline to deploy to Docker Hub

on:
  push:
    branches:
      - 'development'
      - 'master'
      
jobs:

  deploy:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Code
      uses: actions/checkout@v3
            
    - name: Fetch Latest Version
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV

    - name: Get Commit ID & Branch Name
      run: |
        HASH=$(git rev-parse --short "$GITHUB_SHA")
        echo "COMMIT_ID=$HASH" >> $GITHUB_ENV
        echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build & tag Docker image to Docker Hub
      run: |
        docker build  -t mayureshms/python-flask:${{ env.BRANCH_NAME }}-${{ env.COMMIT_ID }}-${{ env.VERSION }} .
        docker push mayureshms/python-flask:${{ env.BRANCH_NAME }}-${{ env.COMMIT_ID }}-${{ env.VERSION }}


    
